apiVersion: v1
kind: Service
metadata:
  name: invoice-api-service
spec:
  type: NodePort
  selector:
    app: invoice-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080