#name: CD - Deploy to EKS
#
#on:
#  workflow_dispatch:
#
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Configure AWS credentials
#        uses: aws-actions/configure-aws-credentials@v2
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: ${{ secrets.AWS_REGION }}
#
#      - name: Update kubeconfig for EKS cluster
#        run: |
#          aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}
#
#      - name: Replace imagePullPolicy and ECR image in deployment.yaml
#        run: |
#          ECR_IMAGE="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest"
#          sed -i "s|image: .*|image: $ECR_IMAGE|g" invoice-api/k8s/deployment.yaml
#          sed -i "s|imagePullPolicy: Never|imagePullPolicy: Always|g" invoice-api/k8s/deployment.yaml
#
#      - name: Deploy to EKS
#        run: |
#          kubectl apply -f invoice-api/k8s/
